// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczviIZnZ608E_hXYI0FSCcgOzSgQylCM',
    appId: '1:838881078541:web:a1aa17057638c42a155444',
    messagingSenderId: '838881078541',
    projectId: 'vighnesh-appdev',
    authDomain: 'vighnesh-appdev.firebaseapp.com',
    storageBucket: 'vighnesh-appdev.firebasestorage.app',
    measurementId: 'G-3GVPQT4X6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rGCpDai5daNnANvboGFvrPRK8sVexcs',
    appId: '1:838881078541:android:631f6aeb8416cfdf155444',
    messagingSenderId: '838881078541',
    projectId: 'vighnesh-appdev',
    storageBucket: 'vighnesh-appdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVl5zOMkGCICUX5gVbV4SYjJGIlobyj-M',
    appId: '1:838881078541:ios:2780a64986afb907155444',
    messagingSenderId: '838881078541',
    projectId: 'vighnesh-appdev',
    storageBucket: 'vighnesh-appdev.firebasestorage.app',
    iosBundleId: 'com.example.firebasetodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVl5zOMkGCICUX5gVbV4SYjJGIlobyj-M',
    appId: '1:838881078541:ios:2780a64986afb907155444',
    messagingSenderId: '838881078541',
    projectId: 'vighnesh-appdev',
    storageBucket: 'vighnesh-appdev.firebasestorage.app',
    iosBundleId: 'com.example.firebasetodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczviIZnZ608E_hXYI0FSCcgOzSgQylCM',
    appId: '1:838881078541:web:53d82dd95cbe78c0155444',
    messagingSenderId: '838881078541',
    projectId: 'vighnesh-appdev',
    authDomain: 'vighnesh-appdev.firebaseapp.com',
    storageBucket: 'vighnesh-appdev.firebasestorage.app',
    measurementId: 'G-QE81DC8MWM',
  );

}